apiVersion: v1
kind: Service
metadata:
  name: rabbit-cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rabbit.port }}
      protocol: TCP
  selector:
    components: {{ .Values.rabbit.components }}

