apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbit.name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: {{ .Values.rabbit.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.rabbit.components }}
    spec:
      containers:
        - name: {{ .Values.rabbit.name }}
          image: "{{ .Values.rabbit.image}}:{{ .Values.rabbit.version }}"
          ports:
            - containerPort: {{ .Values.rabbit.port }}
          env:
            {{- range .Values.rabbit.envs }}
            {{- $data := dict "name" $.Values.secrets.name "env" . }}
            {{- include "env.template" $data | indent 12 }}
            {{- end }}
          resources:
            limits: {{ .Values.rabbit.limits | toYaml | nindent 14 }}
          volumeMounts:
            - name: {{ .Values.rabbit.name }}-data
              mountPath: /var/lib/rabbitmq
              subPath: rabbitmq
      volumes:
        - name: {{ .Values.rabbit.name }}-data
          persistentVolumeClaim:
            claimName: rabbit-pvc