apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      components: rabbit
  template:
    metadata:
      labels:
        components: rabbit
    spec:
      containers:
        - name: rabbit
          image: rabbitmq:3.8.34
          ports:
            - containerPort: 5672
          env:
            - name: SEED_USERNAME
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: SEED_USERNAME
            - name: SEED_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conv-secret
                  key: SEED_USER_PASSWORD
          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"
          volumeMounts:
            - name: rabbit-data
              mountPath: /var/lib/rabbitmq
              subPath: rabbitmq
      volumes:
        - name: rabbit-data
          persistentVolumeClaim:
            claimName: rabbit-pvc