app:
  name: conv-app
  nameApi: conv-api
  image: antonlarichev/conv-app
  components: frontend
  version: 1.2
  port: 80
  limits:
    memory: "512Mi"
    cpu: "200m"

config:
  name: conf-config
  viteDomain: ""

api:
  name: conv-api
  nameApi: conv-api
  image: antonlarichev/conv-api
  components: backend
  version: 1.0
  port: 3000
  limits:
    memory: "512Mi"
    cpu: "300m"
  envs:
    - AMQP_EXCHANGE
    - AMQP_USER
    - AMQP_PASSWORD
    - AMQP_HOSTNAME

service:
  name: conv-service
  nameApi: conv-service
  image: antonlarichev/conv-service
  components: service-backend
  version: 1.0
  port: 3001
  limits:
    memory: "512Mi"
    cpu: "300m"
  envs:
    - AMQP_EXCHANGE
    - AMQP_USER
    - AMQP_PASSWORD
    - AMQP_HOSTNAME
    - AMQP_QUEUE

rabbit:
  name: rabbit
  nameApi: rabbit
  image: rabbitmq
  components: rabbit
  version: 3.8.34
  port: 5672
  limits:
    memory: "512Mi"
    cpu: "300m"
  envs:
    - SEED_USERNAME
    - SEED_USER_PASSWORD

secrets:
  name: conv-secret